Added Pymoo problems
automl/CARP-S pull request #118
Opened 2024-05-26 10:22 UTC by Sohambasu07

Title: Adding `Pymoo` problems as a benchmark to CARP-S

[//]: <> (This is also a comment.)
[//]: <> (Here begins the actual PR body)

This PR adds the problems from [pymoo](https://github.com/anyoptimization/pymoo/tree/main).

## Checks made

This benchmark was ran on the following optimizer:
* smac20 multiobjective using `python carps/run.py +optimizer/smac20=multiobjective '+problem/Pymoo/MO=glob(*)' seed=1 -m`

## Dependencies

The file `pymoo_pip_freeze.txt` contains the `pip freeze` version of the environment that ran the above tests locally.

## Features

The key features of this addition includes:

Multi-objective problems:
* kursawe
* omnitest
* sympart, sympart_rotated
* zdt1, zdt2, zdt3, zdt4, zdt5, zdt6

## Note

smac20-multiobjective doesn't have any solutions for  `sympart` and `sympart_rotated` . I've checked and the `_evaluate()` function in `pymoo.py` does return the costs as expected but for some reason smac doesn't pick up on those and always returns costs as 0.0

[//]: <> (Any explicit consideration that had to be made, any limitations, or the exact scope, and possible future extensions)

2024-05-26 10:54 UTC, benjamc requested changes

2024-05-26 10:54 UTC, benjamc commented on carps/configs/problem/Pymoo/MO/kursawe.yaml
> +  n_trials: 50
fix n trials / use yahpo formula

2024-05-26 11:57 UTC, benjamc approved these changes

2024-05-26 11:59 UTC, merged

2024-05-29 06:49 UTC, eddiebergman reviewed
Looks good from a glance of someone who doesn't know PyMOO. Main question is just how are the `n_trials` determined for the task?

2024-05-29 06:49 UTC, eddiebergman commented on carps/benchmarks/pymoo.py
> +        hps = [Float(name=f"x{i}", bounds=[xl[i], xu[i]]) for i in range(n_var)]
None of them log scaled?

Pretty sure `pymoo` should be safe but you're assuming `n_var` and `xl, xu` are the same size. Could make it more explicit with an `assert`.

2024-05-29 06:49 UTC, eddiebergman commented on carps/benchmarks/yahpo.py
> +    "val_cross_entropy": True,
Nice fix to sneak in ;)

2024-05-29 06:49 UTC, eddiebergman commented on carps/configs/problem/Pymoo/MO/kursawe.yaml
> +  n_trials: 90
@benjamc is there any guidelines on what the `n_trials` should be?

2024-05-29 06:49 UTC, eddiebergman commented on carps/configs/problem/Pymoo/MO/omnitest.yaml
> +  n_trials: 77
@benjamc Likewise here. Where did you get these numbers from @Sohambasu07

2024-05-29 09:18 UTC, Sohambasu07 commented
> Looks good from a glance of someone who doesn't know PyMOO. Main question is just how are the `n_trials` determined for the task?

So @benjamc sent me the code for determining the `n_trials`. It's a formula from YAHPO.

```python
# Formula from YAHPO paper
def get_n_trials(dimension: int) -> int:
    return int(np.ceil(20 + 40 * np.sqrt(dimension)))
```

2024-05-29 09:19 UTC, Sohambasu07 commented on carps/benchmarks/yahpo.py
> +    "val_cross_entropy": True,
Thanks for spotting it during the meeting :)

2024-05-29 09:38 UTC, Sohambasu07 commented on carps/benchmarks/pymoo.py
> +        hps = [Float(name=f"x{i}", bounds=[xl[i], xu[i]]) for i in range(n_var)]
Nope. I didn't find any of them to be log-scaled.
I found it (here)[https://github.com/anyoptimization/pymoo/blob/main/pymoo/core/problem.py#L213-L223] that they convert `xl` and `xu` to ndarrays `if n_vars > 1`.
But I could add an assert just in case.

2024-05-29 10:22 UTC, benjamc commented on carps/configs/problem/Pymoo/MO/omnitest.yaml
> +  n_trials: 77
![grafik](https://github.com/automl/CARP-S/assets/75323339/6b5e9ea1-13c4-489a-a913-0c03b6106112)

2024-05-29 10:22 UTC, benjamc commented on carps/configs/problem/Pymoo/MO/omnitest.yaml
> +  n_trials: 77
which is the magic yahpo formula
though only for single objective but hey, it is citeable

2024-05-29 10:23 UTC, benjamc commented on carps/benchmarks/yahpo.py
> +    "val_cross_entropy": True,
😎