Docs/improve documentation
automl/CARP-S pull request #128
Opened 2024-06-03 12:12 UTC by sarah-segel

2024-06-03 14:05 UTC, benjamc requested changes

2024-06-03 14:05 UTC, benjamc commented on docs/guides/first-steps.md
> +`SMAC2.0` on `BBOB` directly with Hydra:
add install commands again

2024-06-03 14:05 UTC, benjamc commented on docs/contributing/contributing-an-optimizer.md
> +
add reference to template repo https://github.com/automl/CARP-S-template/blob/main/my-optimizer.py

2024-06-04 08:07 UTC, sarah-segel commented on docs/contributing/contributing-an-optimizer.md
> +
Added.

2024-06-04 08:07 UTC, sarah-segel commented on docs/guides/first-steps.md
> +`SMAC2.0` on `BBOB` directly with Hydra:
Right, I added the link to the install instructions (to not have the instructions itself in two places).

2024-06-04 08:15 UTC, merged