Docs/improve docs
automl/CARP-S pull request #131
Opened 2024-06-04 14:42 UTC by sarah-segel

Changes to Readme:
- Removed class diagram instructions
- Moved containerization instructions to docs
- Moved database instructions to docs
- Add link to docs for instructions on contributing benchmarks/optimizers

Others:
- Minimal Hydra section
- Add combined benchmark footprint viz code to notebook

2024-06-04 14:59 UTC, benjamc requested changes

2024-06-04 14:59 UTC, benjamc commented on docs/contributing/contributing-a-benchmark.md
> +3. **Requirements file**: Create a requirements file under
add: the filestructure must be `container_recipes/<benchmark_id>/<benchmark_id>_requirements.txt`

2024-06-04 14:59 UTC, benjamc commented on docs/contributing/contributing-an-optimizer.md
> +
`container_recipes/optimizers/<optimizer_container_id>/<optimizer_container_id>_requirements.txt`

2024-06-04 14:59 UTC, benjamc commented on docs/installation.md
> +mkdir data; cd data; git clone https://github.com/slds-lmu/yahpo_data
`python container_recipes/benchmarks/YAHPO/prepare_YAHPO.py`

2024-06-05 07:55 UTC, sarah-segel commented on docs/contributing/contributing-a-benchmark.md
> +3. **Requirements file**: Create a requirements file under
It still is `container_recipes/benchmarks/<benchmark_id>/<benchmark_id>_requirements.txt`, right? Added.

2024-06-05 07:55 UTC, sarah-segel commented on docs/contributing/contributing-an-optimizer.md
> +
Added.

2024-06-05 07:55 UTC, sarah-segel commented on docs/installation.md
> +mkdir data; cd data; git clone https://github.com/slds-lmu/yahpo_data
Added (also for MFPBench + HPOB).

2024-06-05 08:08 UTC, merged